version: "2.1"
services:
  blender:
    #    image: lscr.io/linuxserver/blender:latest
    build: .
    container_name: blender
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
    volumes:
      - ./projects:/projects
    working_dir: /projects
    ports:
      - 13000:3000
      - 13001:3001
    restart: unless-stopped
